server:
  port: 8764

  servlet:
    context-path: /orderservice

spring:

  application:
    name: orderservice

  datasource:
    url: jdbc:postgresql://localhost:5433/order_db

    username: order_user

    password: order_password

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

  flyway:
    enabled: true

    baseline-on-migrate: true

    locations: classpath:db/migration

  kafka:

    bootstrap-servers: localhost:9092

    producer:

      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:

      group-id: order-group

      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:

        spring.json.trusted.packages: "*"

springdoc:

  swagger-ui:
    path: /swagger-ui.html